services:
  postgres:
    image: postgres:14-alpine
    container_name: strapi-db
    env_file: .env
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - ./data:/data/postgres
    ports:
      - "5432:5432"
